detector:
  identifier: cifar_ood_glow/logit_deq
  config_file: glow.yml
  ckpt_file: model_best.pkl
detector_aug: null
alias: glow
blackbox_only: false
no_grad_predict: true 
indist_dataset: CIFAR10
