detector:
  identifier: cifar_ood_md/md_resnet
  config_file: md_resnet_cifar.yml
  ckpt_file: resnet_cifar10.pth
  lr_tuned_with: SVHN_OOD
detector_aug:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
alias: md
blackbox_only: true 
no_grad_predict: false 
indist_dataset: CIFAR10
