detector:
  identifier: cifar_ood_prood/prood_3
  config_file: prood_3.yml
  ckpt_file: prood_3.pt
detector_aug: null
blackbox_only: false
no_grad_predict: True 
alias: prood 
indist_dataset: CIFAR10
