detector:
  identifier: cifar_ood_atom/rowl
  config_file: rowl.yml
  ckpt_file: checkpoint_100.pth.tar
detector_aug: null
alias: rowl
blackbox_only: false
no_grad_predict: true 
indist_dataset: CIFAR10
