detector:
  identifier: cifar_ood_due/sngp
  config_file: sngp.yml
  ckpt_file: sngp.pt
detector_aug: 
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
detector_no_grad: True 
alias: sngp
