detector:
  identifier: cifar_ood_due/due
  config_file: due.yml
  ckpt_file: due.pt
detector_aug: 
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
alias: due
blackbox_only: false
no_grad_predict: true 
indist_dataset: CIFAR10
