detector:
  identifier: cifar_ood_pixelcnn/f80
  config_file: f80.yml
  ckpt_file: model_best.pkl
detector_aug: null
alias: pixelcnn
blackbox_only: false
no_grad_predict: true 
indist_dataset: CIFAR10
