detector:
  identifier: cifar_ood_atom/atom
  config_file: atom.yml
  ckpt_file: checkpoint_100.pth.tar
detector_aug: null
alias: atom
blackbox_only: false
no_grad_predict: true 
indist_dataset: CIFAR10
