detector:
  identifier: cifar_ood_ae/ghosh_z128
  config_file: ghosh_z128.yml
  ckpt_file: model_best.pkl
detector_aug: null
alias: ae
blackbox_only: false
no_grad_predict: true 
indist_dataset: CIFAR10
