advdist:
  name: adtr
  transform: affineV0
  z_bound: [0, 1]
  sampler: 
    name: langevin
    noise_std: 0.1
    clip_langevin_grad: 0.1
    n_step: 2000
    bound: [0, 1]
    T: 1
    initial_dist: uniform
    sample_shape: [5]
    mh: True
  blackbox: False
data:
  indist_val:
    dataset: CIFAR10_OOD 
    path: datasets
    split: validation 
    batch_size: 128
    n_workers: 4
  indist_test:
    dataset: CIFAR10_OOD 
    path: datasets
    batch_size: 128
    n_workers: 4
    split: evaluation 
  out_eval:
    dataset: SVHN_OOD 
    path: datasets
    split: evaluation 
    batch_size: 500 
    n_workers: 4
