detector:
  identifier: rimgnet_ood_prood/prood_4
  config_file: prood_4.yml
  ckpt_file: prood_4.pt
detector_aug: null
alias: prood 
indist_dataset: RImgNet
blackbox_only: false 
no_grad_predict: true 
