detector:
  identifier: rimgnet_ood_vit/hf
  config_file: vit_md.yml
  ckpt_file: pytorch_model.bin
detector_aug:
  vit_eval: 
    size: 224
detector_no_grad: True
alias: vit_hf_md
indist_dataset: RImgNet 
