advdist:
  name: adae
  T: 0.1
  classifier_thres_logit : -1
  classifier_mean: [0.4914, 0.4822, 0.4465]
  classifier_std: [0.2023, 0.1994, 0.2010]
  model: 'mh'
  z_shape: [64, 1, 1]
  stepsize: 0.1
  n_step: 10000
  z_bound: 1
  ae:
    identifier: celeba32_ood_ae/z64nh8
    config_file: z64nh8.yml
    ckpt_file: model_epoch_300.pkl
  classifier:
    identifier: cifar_v_celeba32/res50norm
    config_file: res50norm.yml
    ckpt_file: model_epoch_50.pkl
    testtimeaug: True
detector:
  identifier: cifar_ood_csi
  config_file: csi.yml
  ckpt_file: 'Null'
  model_path: cifar10_unlabeled.model
  shift_path: feats_10_resize_fix_0.54_cifar10_train_shift.pth
  simclr_path: feats_10_resize_fix_0.54_cifar10_train_simclr.pth
detector_aug: null
detector_no_grad: True 
data:
  indist_val:
    dataset: CIFAR10_OOD 
    path: datasets
    split: validation 
    batch_size: 128
    n_workers: 4
  indist_test:
    dataset: CIFAR10_OOD 
    path: datasets
    batch_size: 128
    n_workers: 4
    split: evaluation 
  out_val:
    dataset: CelebA_OOD 
    path: datasets
    split: validation 
    batch_size: 128
    n_workers: 4
    size: 32
attack:
  n_sample: 1000
  batch_size: 250
