advdist:
  name: adae
  T: 0.1
  classifier_thres_logit : -5
  classifier_mean: [0.4914, 0.4822, 0.4465]
  classifier_std: [0.2023, 0.1994, 0.2010]
  model: 'mh'
  z_shape: [32, 1, 1]
  stepsize: 0.1
  n_step: 2000
  z_bound: 1
  ae:
    identifier: svhn_ood_ae/z32nh8augjitter/run
    config_file: z32nh8augjitter.yml
    ckpt_file: model_epoch_300.pkl
    root: results
  classifier:
    identifier: cifar_v_svhn/res50norm
    config_file: res50norm.yml
    ckpt_file: model_epoch_10.pkl
    testtimeaug: True
detector:
  identifier: cifar_ood_oe_scratch/allconv
  config_file: oe_scratch_allconv.yml
  ckpt_file: cifar10_allconv_oe_scratch_epoch_99.pt
  network: allconv
  num_classes: 10
detector_aug:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2471, 0.2435, 0.2615]
detector_no_grad: True 
data:
  indist_val:
    dataset: CIFAR10_OOD 
    path: datasets
    split: validation 
    batch_size: 128
    n_workers: 4
  indist_test:
    dataset: CIFAR10_OOD 
    path: datasets
    batch_size: 128
    n_workers: 4
    split: evaluation 
  out_val:
    dataset: SVHN_OOD 
    path: datasets
    split: validation 
    batch_size: 128
    n_workers: 4
attack:
  n_sample: 1000
  batch_size: 250
