advdist:
  name: adae
  T: 0.1
  classifier_thres : 0.5
  model: 'mh'
  z_shape: [64, 1, 1]
  stepsize: 0.1
  n_step: 2000
  z_bound: 1
  ae:
    identifier: cifarsvhn_ood_ae/z64
    config_file: z64.yml
    ckpt_file: model_epoch_500.pkl
  classifier:
    identifier: cifar_v_svhn/res50
    config_file: res50.yml
    ckpt_file: model_best.pkl
detector:
  identifier: cifar_ood_oe_scratch/allconv
  config_file: oe_scratch_allconv.yml
  ckpt_file: cifar10_allconv_oe_scratch_epoch_99.pt
  network: allconv
  num_classes: 10
detector_aug:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2471, 0.2435, 0.2615]
detector_no_grad: True 
data:
  indist_val:
      dataset: CIFAR10_OOD 
      path: datasets
      batch_size: 128
      n_workers: 8
      split: validation 
  indist_test:
      dataset: CIFAR10_OOD 
      path: datasets
      batch_size: 128
      n_workers: 8
      split: evaluation 
attack:
  n_sample: 6000
  batch_size: 250
