advdist:
  mode: reinforce
  flow: False
  T: 1.
  model:
    arch: glow 
    x_dim: 3
    x_size: 32
    hidden_channels: 512 
    K: 32
    L: 1
    actnorm_scale: 1.0
    prior_type: gaussian
    do_logit_transform: True 
    dequant_offset: True
    vector_mode: False
    flow_permutation: invconv
    flow_coupling: affineV2 
detector:
  identifier: cifar_glow/logit_deq
  config_file: glow.yml
  ckpt_file: model_best.pkl
  kwargs:
logger: base
training:
  n_iter: 10
  batch_size: 64
  print_interval: 1
  val_interval: 5
  save_interval: 5
  optimizer:
    name: adam
    lr: 1e-4
