trainer: dvd 
logger: base 
model:
    arch: resnetcls
    net: resnet18
    n_class: 1
    pretrained: True
data:
    D0_train:
        dataset: MNISTpad_OOD 
        path: datasets
        batch_size: 128
        n_workers: 8
        split: training
        shuffle: True
    D0_val:
        dataset: MNISTpad_OOD 
        path: datasets
        batch_size: 128
        n_workers: 8
        split: validation 
    D1_train:
        dataset: FashionMNISTpad_OOD 
        path: datasets
        batch_size: 128
        split: training 
        n_workers: 8
        shuffle: True
    D1_val:
        dataset: FashionMNISTpad_OOD 
        size: 128
        path: datasets
        batch_size: 128
        n_workers: 8
        split: validation
training:
    n_epoch: 10
    optimizer:
      name: 'adam'
      lr: 1e-4
    print_interval: 500
    val_interval: 2000
    save_interval: 2000
    save_only_best: True
