advdist:
  name: adtr
  transform: affineV2
  z_bound: [0, 1]
  sampler: 
    name: random
    n_step: 2000
    bound: [0, 1]
    initial_dist: uniform
    sample_shape: [5]
  blackbox: True 
data:
  indist_val:
    dataset: RImgNet 
    path: datasets
    split: validation 
    batch_size: 128
    n_workers: 4
  indist_test:
    dataset: RImgNet 
    path: datasets
    batch_size: 128
    n_workers: 4
    split: evaluation 
  out_eval:
    dataset: EuroSAT 
    path: datasets
    split: evaluation 
    batch_size: 500 
    n_workers: 4
    size: 224
