advdist:
  name: adstylegan2
  stylegan2_g:
    arch: stylegan2_g
    identifier: fgvc_stylegan2/ada_test_bigparam_z16
    config_file: generator.yml
    ckpt_file: model=G_ema-current-weights-step=200000.pth
  sampler: 
    name: mh
    stepsize: 0.1
    n_step: 2000
    bound: spherical
    T: 1
    initial_dist: uniform_sphere
    sample_shape: [16]
  truncation_psi: 0.9
  resize: 224
data:
  indist_val:
    dataset: RImgNet 
    path: datasets
    split: validation 
    batch_size: 128
    n_workers: 4
  indist_test:
    dataset: RImgNet 
    path: datasets
    batch_size: 128
    n_workers: 4
    split: evaluation 
  out_eval:
    dataset: FGVC 
    path: datasets
    split: evaluation 
    batch_size: 500 
    n_workers: 4
    size: 32
