trainer: dvd 
logger: base 
model:
    arch: resnetcls
    net: resnet50
    n_class: 1
    pretrained: True
data:
    D0_train:
        dataset: CIFAR100_OOD 
        path: datasets
        batch_size: 128
        n_workers: 8
        split: training
        shuffle: True
        augmentations:
          hflip:
            p: 0.5
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
        dequant:
          UniformDequantize: {}
    D0_val:
        dataset: CIFAR100_OOD 
        path: datasets
        batch_size: 128
        n_workers: 8
        split: validation 
        augmentations:
          hflip:
            p: 0.5
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
    D1_train:
        dataset: CIFAR10_OOD 
        path: datasets
        batch_size: 128
        split: training 
        n_workers: 8
        shuffle: True
        augmentations:
          hflip:
            p: 0.5
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
        dequant:
          UniformDequantize: {}
    D1_val:
        dataset: CIFAR10_OOD 
        size: 128
        path: datasets
        batch_size: 128
        n_workers: 8
        split: validation
        augmentations:
          hflip:
            p: 0.5
          normalize:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
training:
    n_epoch: 101
    optimizer:
      name: 'adam'
      lr: 1e-5
    print_interval: 500
    val_interval: 2000
    save_interval: 2000
    save_only_best: True
    save_interval_epoch: 5
    clip_grad: null
