trainer: dvd 
logger: base 
model:
    arch: resnetcls
    net: resnet50
    n_class: 1
    pretrained: True
data:
    D0_train:
      concat1:
        dataset: SVHN_OOD 
        path: datasets
        split: training
        dequant:
          UniformDequantize: {}
      concat2:
        dataset: CelebA_OOD 
        path: datasets
        split: training
        size: 32
        augmentations:
          hflip:
            p: 0.5
        dequant:
          UniformDequantize: {}
      shuffle: True
      n_workers: 8
      batch_size: 128
    D0_val:
      concat1:
        dataset: SVHN_OOD 
        path: datasets
        split: validation 
      concat2:
        dataset: CelebA_OOD 
        path: datasets
        split: validation 
        size: 32
      shuffle: True
      n_workers: 8
      batch_size: 128
    D1_train:
        dataset: CIFAR10_OOD 
        path: datasets
        batch_size: 128
        split: training 
        n_workers: 8
        shuffle: True
        augmentations:
          hflip:
            p: 0.5
        dequant:
          UniformDequantize: {}
    D1_val:
        dataset: CIFAR10_OOD 
        size: 128
        path: datasets
        batch_size: 128
        n_workers: 8
        split: validation
training:
    n_epoch: 101
    optimizer:
      name: 'adam'
      lr: 1e-5
    print_interval: 500
    val_interval: 2000
    save_interval: 2000
    save_only_best: True
    save_interval_epoch: 5
