advdist:
  name: adae
  T: 0.1
  classifier_thres : 0.9
  model:
    arch: glow 
    x_dim: 32 # z_dim
    x_size: 1
    hidden_channels: 32 
    K: 32
    L: 1
    actnorm_scale: 1.0
    flow_permutation: invconv
    flow_coupling: affineV2 
    vector_mode: True
  ae:
    identifier: cifarsvhn_ood_ae/z32
    config_file: z32.yml
    ckpt_file: model_epoch_300.pkl
  classifier:
    identifier: cifar_v_svhn/res18_lr5
    config_file: res18.yml
    ckpt_file: model_best.pkl
    logit: True
detector:
  identifier: cifar_ood_nae/z32gn
  config_file: z32gn.yml
  ckpt_file: nae_8.pkl
data:
  indist_train:
      dataset: CIFAR10_OOD 
      path: datasets
      batch_size: 32
      n_workers: 8
      split: validation 
logger: base
training:
  n_iter: 500
  batch_size: 32
  print_interval: 10
  val_interval: 10
  save_interval: 400
  optimizer:
    name: adam
    lr: 1e-4
